### ISSUE TITLE
Does not work on PostgreSQL

### ISSUE THREAD

**Issue by mudrd8mz** [MNaveenkumar/moodle-block_logreport#1]
Date/time related functions like `FROM_UNIXTIME` or `DATEDIFF` are not cross-db compatible and cause the plugin fail terribly on non-mysql sites:

![image](https://user-images.githubusercontent.com/85831/45649883-eac9f980-bacc-11e8-8d3d-4b8477612b2e.png)

Please refer to https://docs.moodle.org/dev/Plugin_contribution_checklist#Cross-DB_compatibility

**Comment by MNaveenkumar** [comment]
Thanks for posting issue, tested in postgreSQL. 
Removed charts for postgresSQL database applications. It will works fine now for both MySQL and PostgreSQL.
