### ISSUE TITLE
Please review capability checking in all files.

### ISSUE THREAD

**Issue by danmarsden** [MNaveenkumar/moodle-block_logreport#11]
I see you have added:
require_capability('report/log:view', $context);

to ajax.php - but I do not see a similar call in server_processing.php - allowing anyone enrolled in the course to download logs.

Ideally your plugin should also implement it's own capabilities rather than re-using capabilities from report/log.

**Comment by MNaveenkumar** [comment]
Add require_capability to server_processing file also.
