### ISSUE TITLE
MySQL specific functions

### ISSUE THREAD

**Issue by danmarsden** [MNaveenkumar/moodle-block_logreport#12]
Plugins submitted to the plugins database must support postgres/mysql - I see a significant amount of functionality wrapped in an "if Mysql" call - typically we don't allow this sort of thing in the plugins db.

If this is "extra" functionality and your plugin is still functional with postgres you could make it very clear in your plugins db description that your plugin does not provide all features when installed in a postgres site, we could then discuss this as a plugin review team and decide if we can approve - personally I think you should spend some time making it cross-db compatible.

**Comment by MNaveenkumar** [comment]
Complete functionality available now for both mysql and postgres

**Comment by luisdev** [comment]
> 
> Complete functionality available now for both mysql and postgres

Are MSSQL and Oracle included, since Moodle also supports those two platforms?

**Comment by danmarsden** [comment]
FYI - Moodle Plugin guardians don't test MS SQL or Oracle support prior to approval in the plugins db, but we do try to keep an eye out for sql that might be incompatible.

Typically sites that want to use MS Sql or Oracle will need to test plugins on their own to determine compatibility.
