### ISSUE TITLE
css not specific enough.

### ISSUE THREAD

**Issue by danmarsden** [MNaveenkumar/moodle-block_logreport#5]
all custom css added by the pluigin should be very specific - typically content will only be displayed within the block so you should be able to prefix all css with:
.block_logreport
eg:
```
.block_logreport #viewreport {
```
It would be good to move all the css you have in the style folder into the main style.css file as well.

**Comment by MNaveenkumar** [comment]
Updated prefix.
I am using external plugins like datatables, select2 and jquery UI. Just want to keep it separate folder from main CSS file.

**Comment by danmarsden** [comment]
Moodle combines all css found in modules styles.css files into a single file and manages the caching of that file really well - by moving your css into separate files you lose the benefits from cached css. It would still be good for you to move this into the main styles.css file instead of individually including css files.
